### PR TITLE
Replacing bitcore-message package by bitcoinjs-message.

### LINKED ISSUE #1: Npm audit shows a vulnerable dependencie
```bash
$ npm audit # using npm 6.1.0
=== npm audit security report ===                        
                                                                                
# Run  npm install bitcore-lib@8.0.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bitcore-lib                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bitcore-lib > lodash                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bitcore-message                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bitcore-message > bitcore-lib > lodash                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 low severity vulnerabilities in 250 scanned packages
  1 vulnerability requires semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```

### PR DESCRIPTION
**Pull request by RiadVargas**
This PR intends to close #1 by replacing `bitcore-message` since it's no longer maintained by Bitpay (last release was almost 2 years ago and had an outdated dependency on `bitcore-lib`).

Ideally we should migrate to both bitcoinjs packages (`lib` and `message`) but it will demand extra time to refactor to avoid breaking compatibility.

:warning: Please do not merge it yet, I will do further tests and sign commits.

### CODE REVIEW

**Comment by RiadVargas** [comment]
Output of `npm audit` running on npm's 6.6.0 version:
```➜  walltime-cli git:(fixing-security-issues) ✗ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 410 scanned packages```

**Comment by felipelalli** [comment]
@RiadVargas I'll make a new release soon. Can I merge this or not yet?

**Comment by RiadVargas** [comment]
@felipelalli Yes, you can. I've properly signed both commits.

**Comment by felipelalli** [comment]
Ok, thank you!

**Pull request merged**
